### ISSUE TITLE
Button on ViewPager Child layout not clickable when DrawerFromBackTransformation is applied

### ISSUE THREAD

**Issue by WanClem** [geftimov/android-viewpager-transformers#6]
Nice job on ViewPagerTransformers, I tried applying the DrawerFromBackTransformer to my viewpager and everything worked well,however I got a problem...I have a button in each of my viewpager layouts and they are not clickable when this transformation is applied to the viewpager.If I remove the transformation everything works fine.......What should I do? Thanks

**Comment by geftimov** [comment]
I can not replicate it, sorry.

**Comment by maciej-kaznowski** [comment]
I too am experiencing this issue. However I see that the touch events are actually happening in the 1st page of the ViewPager, rather than in the correct page. This means that when I scroll in my 2nd page, the 1st page actually scrolls.

**Comment by sebinpaul** [comment]
I'm too experiencing this issue. My viewpager has 5 fragments. Each fragment has a RecyclerView. If i click an item of fragment 1's recyclerview, fragment 2's recyclerview item is clicked. Is the issue resolved or is there a workaround?

**Comment by geftimov** [comment]
@sebinpaul Does all of your fragments have solid background?

**Comment by sebinpaul** [comment]
All the fragments have transparent background and it is a must have for my app.

**Comment by geftimov** [comment]
That is unfortunately problem with fragments when they are added on top of each other.
You can try to make all of them clickable.
Hope it helps.

**Comment by kibotu** [comment]
tried it with the clickable background, doesn't seem to do the trick for me :(
